title: "Local Digital Project: Chatbots and AI"
author: "Blog Author"
description: "Website and Repo for the collaborative project"
more: "read more Â»"
url: "https://LocalDigitalChatbots.github.io/"
baseurl: "/website"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - github: "https://github.com/LocalDigitalChatbots"
  - envelope: "mailto:nlawrence@oxford.gov.uk"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
